In [4]:
import mysql.connector as mysql

cnx = mysql.connect(user = 'root', passwd = 'root', host = 'localhost', db='set_cover')

cursor = cnx.cursor()

cursor.callproc('spdemand')

results = []

for result in cursor.stored_results():
    results.append(result.fetchall())

cursor.close()
cnx.close()

[demand] = results
print(len(demand))
print(demand[:5])

ProgrammingError: 1305 (42000): PROCEDURE set_cover.spdemand does not exist

In [29]:
cnx = mysql.connect(user = 'root', passwd = 'root', host = 'localhost', db='set_cover')

cursor = cnx.cursor()

cursor.callproc('tower')

results = []

for result in cursor.stored_results():
    results.append(result.fetchall())

cursor.close()
cnx.close()

[tower] = results
print(len(tower))
print(tower[:5])

4489
[(0.0, 0.0), (0.0, 15.0), (0.0, 30.0), (0.0, 45.0), (0.0, 60.0)]


In [92]:
list = []
for i in tower:
    for j in demand:
        x = np.sqrt((i[0] - j[0])**2 + (i[1] - j[1])**2)
        if x <= 100:
            list.append(1)
        else:
            list.append(0)

In [100]:
subsets = np.array(list)
subsets = subsets.reshape(2000, 4489, order = 'F')
print(subsets.shape)
subsets

(2000, 4489)


array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 1, 1, ..., 0, 0, 0]])

In [24]:
import numpy as np
import gurobipy as gpy

num_var = 1
done = False

while not done:
    m = gpy.Model('Cell')
    #m.setParam('MIPGap', 0.08)
    x = m.addMVar((num_var,), vtype=gpy.GRB.BINARY)
    m.update()
    m.setObjective(x.sum(), gpy.GRB.MINIMIZE)
    m.addConstr(x@subsets)
    m.update()
    m.optimize()
    if m.Status == 3:
        num_var += 1
    else:
        done = True

array([[ 41., 989.],
       [243., 946.],
       [120., 502.],
       ...,
       [787., 270.],
       [934., 631.],
       [ 52.,  99.]])

In [101]:
import numpy as np
import gurobipy as gpy

num_var = 1
done = False

m = gpy.Model('Cell')
    #m.setParam('MIPGap', 0.08)
x = m.addMVar((num_var,), vtype=gpy.GRB.BINARY)
m.update()
m.setObjective(x.sum(), gpy.GRB.MINIMIZE)
m.update()


Set parameter Username
Academic license - for non-commercial use only - expires 2024-11-08


In [98]:
list1 = [0,0,1,1,0,0,0,1,0,0]
y = np.array(list1)
y.reshape(2,5, order = 'F')

array([[0, 1, 0, 0, 0],
       [0, 1, 0, 1, 0]])